services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_fastapi
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/db_fastapi"
    volumes:
      - ./documents:/app/documents

  app_alembic:
    build:
      context: .
    volumes:
        - .:/app
    command: upgrade head
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db_fastapi
    depends_on:
      - db
    entrypoint: ["alembic"]

  celery_worker:
    build: .
    command: celery -A app.celery.celery_app worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/db_fastapi"
    volumes:
      - ./documents:/app/documents
    restart: always
