"""Вторая миграция

Revision ID: 118a338b1dac
Revises: 79eb8afeb6cb
Create Date: 2024-11-12 14:29:11.625708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118a338b1dac'
down_revision = '79eb8afeb6cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_doc', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_doc'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_text')
    # ### end Alembic commands ###
