"""Третья миграция

Revision ID: 603c5f4c50fb
Revises: 118a338b1dac
Create Date: 2024-11-12 14:30:54.158528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603c5f4c50fb'
down_revision = '118a338b1dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_text',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_doc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_doc'], ['documents.id'], name='test_text_id_doc_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_text_pkey')
    )
    # ### end Alembic commands ###
