"""Первая миграция

Revision ID: 79eb8afeb6cb
Revises: 
Create Date: 2024-11-12 14:25:15.394811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79eb8afeb6cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
